# cloudbuild.yaml
steps:
- name: 'docker.io/library/python:3.7'
  id: Test
  entrypoint: /bin/sh
  args: [-c, 'python -m unittest dags/tests/test_python_scripts.py']

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy
  entrypoint: bash
  args: ['-c', 'gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/dags']

- name: 'hashicorp/terraform:1.5.3'
  id: Terraform_Init
  dir: 'terraform'
  entrypoint: 'terraform'
  args: ['init']

- name: 'hashicorp/terraform:1.5.3'
  id: Terraform_Validate
  dir: 'terraform'
  entrypoint: 'terraform'
  args: ['validate']

- name: 'hashicorp/terraform:1.5.3'
  id: Terraform_Plan
  dir: 'terraform'
  entrypoint: 'terraform'
  args: ['plan', '-out=tfplan']

- name: 'bash'
  id: Check_Plan_File
  dir: 'terraform'
  entrypoint: 'bash'
  args: ['-c', '[ -f tfplan ] || exit 1']

- name: 'hashicorp/terraform:1.5.3'
  id: Terraform_Apply_Real
  dir: 'terraform'
  entrypoint: 'terraform'
  args: ['apply', '-auto-approve', 'tfplan']

substitutions:
  _COMPOSER_BUCKET: cs-dataplex-experience-6133-us-east1-composer

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'
  env:
    - 'TF_PLUGIN_CACHE_DIR=/workspace/.terraform/plugins'

